<a href="https://colab.research.google.com/github/shivsharanrupesh/Python_Training/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch==2.4.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.3/797.3 MB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 82.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 74.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 40.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

In [2]:
import torch
torch.cuda.is_available()

False

Creating Pytorch tensors:

In [3]:
#creates a zero-dimension tensor(scalar) from a Python integer
tensor0d = torch.tensor(1)
print(tensor0d)

tensor(1)


In [4]:
#creates a one-dimensional tensor(vector) from a python list
tensor1d = torch.tensor([1,2,3])
print(tensor1d)

tensor([1, 2, 3])


In [5]:
#create a two-dimensional tensor from a nested Python list
tensor2d = torch.tensor([[1,2], [3,4]])
print(tensor2d)

tensor([[1, 2],
        [3, 4]])


In [6]:
#create a 3d tensor from a nester Python list:
tensor3d = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])
print(tensor3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Tensor Data Types:

In [7]:
tensor1d = torch.tensor([1,2,3])
print(tensor1d.dtype)

torch.int64


In [8]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [10]:
float32vec = tensor1d.to(torch.float32)
print(float32vec.dtype)

torch.float32


Common Pytorch Tensor Operations:

In [11]:
tensor2d = torch.tensor([[1,2,3], [4,5,6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
print(tensor2d.shape)

torch.Size([2, 3])


In [14]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [15]:
print(tensor2d.view(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [16]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [17]:
#multiply two matrices:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])
